### ISSUE TITLE
cowdancer workaround bug

### ISSUE THREAD

**Issue by yvlasenko** [mika/jenkins-debian-glue#113]
Cowdancer workaround should check for cowbuilder base distribution, not a host one. When building debian package on ubuntu using pbuilderrc COMPONENTS variables and not exporting COMPONENTS cowbuilder is unable to build base as universe component is unavailable.

Setting COMPONENTS variable fixes the issue but it makes pbuilderrc COMPONENTS variable almost useless.

**Comment by mika** [comment]
Thanks, this issue should be fixed with the mentioned commit!
