### ISSUE TITLE
upload jenkins-debian-glue to the Debian project

### ISSUE THREAD

**Issue by hashar** [mika/jenkins-debian-glue#115]
The glue scripts are so useful they should be uploaded to the Debian project.  The Debian Developers at Wikimedia foundation were wondering why it was not already available.  We ended up rebuilding it and putting it on our own apt.

Let the world easily benefit from the very nice scripts!

**Comment by mika** [comment]
Hej, thanks for this touching feedback. \o/ I was indeed asked by several people already about uploading j-d-g to Debian, so I'm actually considering to do that. :)

JFTR: pre-built Debian packages of j-d-g are available at http://jenkins.grml.org/job/jenkins-debian-glue-binaries/ (latest git/master) and http://jenkins.grml.org/job/jenkins-debian-glue-release-binaries/ (latest stable release).

**Comment by mika** [comment]
I've just uploaded jenkins-debian-glue towards Debian, it should appear on https://ftp-master.debian.org/new.html soonish.

**Comment by mika** [comment]
````Subject: jenkins-debian-glue_0.14.0_amd64.changes ACCEPTED into unstable, unstable````

:)

**Comment by hashar** [comment]
Well done and congratulations!
