### ISSUE TITLE
autopkgtest integration fails the build if tests are skipped

### ISSUE THREAD

**Issue by heftig** [mika/jenkins-debian-glue#129]
If at least one test got skipped (exit 2 from adt-run), B20autopkgtest also exits with 2 and causes the build to fail.

The autopkgtest manpage states:
```
EXIT STATUS
       0    all tests passed
       1    unexpected failure (the python interpreter invents this exit status)
       2    at least one test skipped
       4    at least one test failed
       6    at least one test failed and at least one test skipped
       8    no tests in this package
       12   erroneous package
       16   testbed failure
       20   other unexpected failures including bad usage
```

B20autopkgtest exits with 0 if adt-run status is 4. Shouldn't it also exit 0 if the status is 2, 6 or 8?

Apparently a subsequent invocation of adtsummary_tap is supposed to report failed tests. Is there any documentation on this?

**Comment by mika** [comment]
Great finding, thanks! So I think http://paste.grml.org/hidden/1d0d128e should address this issue?

**Comment by heftig** [comment]
You can do a `case` like:
```bash
adt-run \
  ${OUTPUT_OPTION} "${TMPADT}/out" \
  --summary "${TMPADT}/summary" \
  --built-tree "${PWD}" \
  $binaries ${ADT_OPTIONS:-} --- adt-virt-null
EXIT=$?

case $EXIT in
  2|4|6|8) exit 0 ;; # let adtsummary_tap report the failure
  *) exit $EXIT ;;
esac
```

**Comment by mika** [comment]
* Jan Alexander Steffens [Mon Jul 27, 2015 at 08:14:41AM -0700]:
> You can do a `case` like:
> ```bash
> adt-run \
>   ${OUTPUT_OPTION} "${TMPADT}/out" \
>   --summary "${TMPADT}/summary" \
>   --built-tree "${PWD}" \
>   $binaries ${ADT_OPTIONS:-} --- adt-virt-null
> EXIT=$?

> case $EXIT in
>   2|4|6|8) exit 0 ;; # let adtsummary_tap report the failure
>   *) exit $EXIT ;;
> esac
> ```

Jepp sure, thanks for suggestion. Was asking more in terms of logic.
I'll commit that then!

regards,
-mika-

**Comment by mika** [comment]
Solved via https://github.com/mika/jenkins-debian-glue/commit/026ace2075a6d16312b76e4313fcf5119f28fa1d - thanks for reporting!
