### ISSUE TITLE
Use jenkins-debia-glue with pristine-tar and upstream branches

### ISSUE THREAD

**Issue by djibi2** [mika/jenkins-debian-glue#141]
I have some packages that use the --git-pristine-tar option to build the packages.  Usually, for this kind of build to work you need three branches checked out master (debian), upstream and pristine-tar.

I haven't found any configuration item or environment variables in jenkins-debian-glue or any other plugin that will get all the branches checked out properly.

There is an example on the FAQ that shows this line referencing pristine-tar which make me think this is possible with this tool.
```
gbp:debug: ['git', 'show-ref', 'refs/heads/pristine-tar']
```

Thanks,
Robert

**Comment by mika** [comment]
jenkins-debian-glue supports that workflow out of the box (actually it's the recommended one), so you have nothing to do specially about it (if so it would be a bug :)).

**Comment by djibi2** [comment]
Great thanks, yes it worked out of the box.  I didn't see any mention of this work flow in the documentation.
