### ISSUE TITLE
`/proc/uptime` missing decimal point causing havoc all around

### ISSUE THREAD

**Issue by oerdnj** [mika/jenkins-debian-glue#153]
My `/proc/uptime` output looks like this:
```
# cat /proc/uptime 
16186 0
```
It's an LXC guest, so it might be the culprit, anyway there's a simple fix, first cut the number then remove \..*:
```
  [ -n "$start_seconds" ] && SECONDS="$[$(cut -d ' ' -f 1 /proc/uptime | cut -f 1 -d .)-$start_seconds]" || SECONDS="unknown"
```

**Comment by mika** [comment]
Sorry for the late reply, this should be fixed by 16f0ba5565435e12cb211c686bd5a49cb073252e nowadays. Thanks for reporting and please let me know if there should be any further issues.
