### ISSUE TITLE
Automatic Install issue in Ubuntu 16.04 LTS Server

### ISSUE THREAD

**Issue by mogray5** [mika/jenkins-debian-glue#163]
Hi,
I tried the puppet based installer on a vanilla Ubuntu 16.04 LTS Server and the resulting jenkins-debian-glue-source job build results in the below error:

```
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Finished: FAILURE
```
Also posted in red at the top of the job configuration web page is this message:
```
Jenkins Git plugin v3.0.0
        Jenkins Mailer Plugin v1.17 failed to load. Fix this plugin first.
    Jenkins Mailer Plugin v1.18
        display-url-api v0.2 is missing. To fix, install v0.2 or later.
```
Looking at the source job configuration it looks like the Git setup information is also missing.

I then wiped the machine and instead went through the manual install option and was able to get it working so I suspect there may be an issue withe the puppet installer.

Thanks,
Wayne

**Comment by mika** [comment]
Thanks for reporting this issue, Wayne. This is fixed now.
