### ISSUE TITLE
Subversion error during build of sources package

### ISSUE THREAD

**Issue by mogray5** [mika/jenkins-debian-glue#164]
When building on Ubuntu 16.04 LTS which defaults to subversion 1.9.3 an error is thrown during the svn propget mergeWithUpstream step which causes the build step to fail.  Error snippet below.

On Ubuntu 14.04 LTS with subversion 1.8.8 no error occurs.

```
++ svn propget mergeWithUpstream source//debian
svn: warning: W200017: Property 'mergeWithUpstream' not found on 'source/debian'
svn: E200000: A problem occurred; see other errors for details
+ debian_only=
Build step 'Execute shell' marked build as failure
Archiving artifacts
Recording test results
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
Finished: FAILURE
```

**Comment by mika** [comment]
Thanks for reporting, this should be fixed now, please let me know if you still notice any problems.
