### ISSUE TITLE
Support for .buildinfo files

### ISSUE THREAD

**Issue by ChristophBerg** [mika/jenkins-debian-glue#165]
dpkg-buildpackage in sid will now include .buildinfo files in the .changes files produced.

One of the changes needed to support them is to update the list of files to be archived/copied from/between jobs, e.g. artifacts: '*.gz,*.bz2,*.xz,*.deb,*.dsc,*.changes,*.buildinfo'.

**Comment by mika** [comment]
Thanks for the bugreport, I've pushed a change which addresses that and also updated the instructions at jenkins-debian-glue.org accordingly. Thanks!
