### ISSUE TITLE
Don't remove source packages when building binary only packages

### ISSUE THREAD

**Issue by tonin** [mika/jenkins-debian-glue#173]
When the `MAIN_ARCHITECTURE`  or the host architecture doesn't match the package architecture, we build binary only packages by setting DEBBUILDOPTS to `-B`.  But when looking at packages to remove from the repository, we remove the source package too, although we have nothing to replace it with.

I think we should keep the source package in the repo in that case.

**Comment by mika** [comment]
Good catch. We're talking about https://github.com/mika/jenkins-debian-glue/blob/master/scripts/build-and-provide-package#L780 - right?

**Comment by tonin** [comment]
Yes, that the line.  I have a PR I should be able to propose shortly.

**Comment by tonin** [comment]
Maybe there is a bit of redundancy when setting `SKIP_SOURCE_REMOVAL` but this is every place where the binary builds are being decided.
