### ISSUE TITLE
Use of --no-check-certificate in various places

### ISSUE THREAD

**Issue by CyrilBrulebois** [mika/jenkins-debian-glue#178]
I haven't checked all occurrences but seeing `wget --no-check-certificate` twice in `puppet/apply.sh` and `puppet/jenkins_debian_glue.pp` can make one a bit nervous…

**Comment by mika** [comment]
Fixed via https://github.com/mika/jenkins-debian-glue/commit/066a1c0e4d708b36481ae5c0815854530d7010bb
