### ISSUE TITLE
Multiple running jobs: problem with COWBUILDER_BASE

### ISSUE THREAD

**Issue by linuxmail** [mika/jenkins-debian-glue#184]
Hello,

I want to start multiple jobs, but at the moment it isn't possible, because all of them uses the same COWBUILDER_BASE ENV, which is per default /var/cache/pbuilder/<base-$dist-$arch.cow>. Is it possible to use something like the "${BUILD_NUMBER}" inside the pbuilder jobs?

I tried to set:

```
COWBUILDER_BASE="/var/cache/pbuilder/base-${BUILD_NUMBER}-${COWBUILDER_DIST}-${arch}.cow/"
```
but later COWBUILDER_BASE, is overwritten with the default one:
/var/cache/pbuilder/base-jessie-amd64.cow. I also use the Matrix plugin.

Is there something I missed?

cu denny

**Comment by mika** [comment]
What exactly is the problem with multiple jobs running at the same tame and using the same cowbuilder base environment?

Regarding setting `COWBUILDER_BASE`, this shouldn't be a problem to overwrite, are you sure you did export the variable, like `export COWBUILDER_BASE="/var/cache/pbuilder/base-${BUILD_NUMBER}-${COWBUILDER_DIST}-${arch}.cow/"`?

**Comment by linuxmail** [comment]
hi Mika,

I'm very sorry for my really long latency ... you are right: I've forgotten the "export". I had to use:

`export COWBUILDER_BASE="/var/cache/pbuilder/base-${BUILD_NUMBER}-${distribution}-${architecture}.cow/"`

to get it working :-)
