### ISSUE TITLE
Error: Architecture $arch as given to --architecture is not know.

### ISSUE THREAD

**Issue by vchrizz** [mika/jenkins-debian-glue#202]
Everything is fine, when I set up a multiconfiguration job the first time. But when I edit it and add another architectures to it, following error occurs on the newly added arch:
```
+ reprepro -A armel -b /srv/repository -v --waitforlock 1000 remove olsrd olsrd-gui-dbgsym
Error: Architecture 'armel' as given to --architecture is not know.
(it does not appear as architecture in /srv/repository/conf/distributions (did you mistype?))
There have been errors!

```
To 'fix' this, either edit /srv/repository/conf/distributions (which seems not to be updated after the job was edited and started again?) via shell and add the architecture, or what also helped is to delete the job (and via shell also remove manually everything related, like builddir, workingdir, lockfiles, configs, ..) then recreate the job from scratch with all architectures added, then it runs through successfully until I add another arch again.

**Comment by mika** [comment]
Yeah, the "workaround" is as you described it, to edit and add the architecture in question (`armel` in your case) to the according repository in `/srv/repository/conf/distributions` if you're adding another architecture in some job.

Fiddling with existing repositories in reprepro isn't really nice, so I'm a bit reluctant to changing our `generate-reprepro-codename` script to modify existing entries. Currently we're exiting as soon as the according repos exists already, see:

```
if grep -q "^\(Codename\|Suite\): ${REPOS}$" "${REPOSITORY}"/conf/distributions ; then
  echo "Codename/repository $REPOS exists already, ignoring request to add again."
...

If someone provides a bullet-proof PR I think we could include it, but I personally feel like that's a wont-fix otherwise. :)

**Comment by vchrizz** [comment]
or maybe you want to add that sidenote about editing existing repositories, didnt know that.
in my case this is not a problem (as i use vagrant and just issue two commands to recreate the whole vm), just wanted to report the issue :)

another thing i noticed (and is not worth a seperate issue), is it possible to remove the datetimestamp from built debian packages at some point of building? i would like to reproduce packages exactly like the ones on debian apt repos but could not find an option yet to remove the `~20181031080444.1` in e.g. filename `olsrd_0.9.6.2-1~20181031080444.1_amd64.deb`

**Comment by mika** [comment]
Regarding the datetimestamp question: either build with the `tag` environment variable set (use the version tag that you want to build, that's the idea of it), or if you want to test it set `SKIP_DCH=true` in the build (this is really to be used with caution, since the _identical version_ of a package can't be re-added into the repository again).

Closing this issue.
