### ISSUE TITLE
Combine common functionality in scripts/generate-{git|svn}-snapshot

### ISSUE THREAD

**Issue by Centuriondan** [mika/jenkins-debian-glue#205]

**Comment by mika** [comment]
Yes that would be nice, I'm not a user of `generate-svn-snapshot` myself anymore though.
If someone is willing to work on this I'm more than happy to accept PRs.

**Comment by Centuriondan** [comment]
I'll see if I can find some time... it struck me as a bit odd that `generate-svn-snapshot` and `generate-git-snapshot` use different paths for building the source package the former using the "recommended" dpkg-source + dpkg-genchanges etc and the later using dpkg-buildpackage...

I noticed when recent versions of dpkg ~1.18 dropped including the orig.tar.?z in the sources.changes and tried to figure out how to force including it...

As an aside I have a bunch of patches in our devuan fork of jdg that I probably should push here too.

**Comment by mika** [comment]
I agree, though that comes from the fact that `generate-git-snapshot` can rely on git-buildpackage for some stuff and only needs to do the final `dpkg-buildpackage` at the end, while we don't have something similar for svn available that works as we'd need it.

**Comment by Centuriondan** [comment]
That said we (Devuan) exclusively use git (currently via gitlab), and I can't see svn's usage growing, particularly now that debian have their own gitlab instance - essentially leaving svn and other vcs's at the mercy of aging git integration support it may simply be not worth worrying about svn.

I would have thought that bringing the common functionality together would be useful - if nothing else to extend the supportability of svn as dpkg tools change

My biggest pain is our very hacky upload process to dak - and that's what started this little bit of introspection ;-)

**Comment by mika** [comment]
Yeah, usage of svn is decreasing and won't be relevant for the ecosystem around Debian anymore IMO. So from my PoV the `generate-svn-snapshot` script will disappear over time, it's really just there in case someone still has a use case for it, though if there should be any problems with it and no one provides working patches for it I'll consider just dropping it.

Thanks for your work on bringing Devuan's j-d-g work back to upstream, appreciated! :)

**Comment by Centuriondan** [comment]
Actually thanks for your continuing work on jdg - it's an essential part of Devuan's infrastructure.

It would be nice if you could bump a new release soon.  We're currently living on the bleeding edge patched up to HEAD on master to get the fixes for autopkgtest etc :-)

**Comment by mika** [comment]
Ah sure, thanks for the reminder - just tagged, pushed + uploaded v0.19.0.

**Comment by Centuriondan** [comment]
Thanks.. that'll need to get into debian pronto because of the deprecated use of adt-* is currently broken for sid and buster.

**Comment by Centuriondan** [comment]
nope - but might be nice to add a pre-emptive `Recommends: jenkins-debian-glue-vendor-profile` to help with #206

**Comment by Centuriondan** [comment]
actually I suppose I should create a PR for #206 with a patch for that and the patch in /etc/jenkins-debian-glue to find the vendor profile

**Comment by Centuriondan** [comment]
closing... not much benefit for the effort
