### ISSUE TITLE
generate-reprepro-codename seems to use SUDO_CMD superfluously

### ISSUE THREAD

**Issue by kienanstewart** [mika/jenkins-debian-glue#220]
Hi,

in generate-reprepro-codename there are two calls which use SUDO_CMD if it is set to become the reprepro user; however, in all cases of calls to this function (from build-and-generate-package), the entire script is already called as the reprepro user.

It seems like usage of SUDO_CMD inside generate-reprepro-codename is now superfluous, and can lead to sudo error spam, eg: 

```
+ sudo -u reprepro mkdir -p /srv/reprepro/conf
reprepro is not in the sudoers file. This event will be reported.
```

**Comment by mika** [comment]
Thanks for providing this bugreport and a PR adressing it, I just need some time to ensure we aren't breaking any stuff out there™, since `generate-reprepro-codename` might also be invoked outside of `build-and-generate-package`).

**Comment by kienanstewart** [comment]
For sure! Thanks for taking the time to look at it
