### ISSUE TITLE
Add a way to set Distribution in changes files

### ISSUE THREAD

**Issue by azatoth** [mika/jenkins-debian-glue#55]
While I thought setting distribution variable  would suffice, it didn't change the Distribution key in the changes file for me (nor in changelog). Trying to set distribution=staging, I 'm ending up with following: "bubba-backend (2.6~rc10+0~1364487385.9+staging~1.gbp483755) precise; urgency=low"

**Comment by mika** [comment]
Sorry for the long time without any reply here. :( You would like to set distribution=staging in the *-source job and then get "$package ($version) $distribution; urgency=low" in debian/changelog, right? You can use "export DIST=staging" in the *-source job before invoking generate-git-snapshot to get this behaviour. To control the behavior of the resulting version string you can use "export distribution=staging" as you already did. I'm aware that this is not elegant and confusing, but reworking this is not so trivial without breaking existing setups. Closing for the time being.
