### ISSUE TITLE
dpkg-source can't find upstream tarball generated in gbp 'export-dir'

### ISSUE THREAD

**Issue by hashar** [mika/jenkins-debian-glue#87]
I have a repository with a debian/gbp.conf as:

    [DEFAULT]
    upstream-tree=branch
    upstream-branch=upstream
    debian-branch=master
    tarball-dir = ../tarballs
    export-dir = ../build-area

The repo is checked out under /source/

When running the generate-git-snapshot command a tarball is properly generated in /build-area/ :

    + git-buildpackage -nc --git-force-create --git-ignore-new --git-ignore-branch -S -us -uc --git-verbose --git-builder=/bin/true --git-cleaner=/bin/true
    gbp:debug: ['git', 'branch', '--no-color']
    gbp:debug: /bin/true [] []
    gbp:debug: ['git', 'branch', '--no-color']
    gbp:debug: Looking for orig tarball 'vips_7.32.3.orig.tar.gz' at '../tarballs'
    gbp:info: Orig tarball 'vips_7.32.3.orig.tar.gz' not found at '../tarballs'
    gbp:info: vips_7.32.3.orig.tar.gz does not exist, creating from 'upstream'
    gbp:debug: ['git', 'ls-tree', 'upstream']
    gbp:debug: Building upstream tarball with compression 'gzip -9'
    gbp:debug: ['git', 'ls-tree', 'HEAD']
    gbp:info: Exporting 'HEAD' to '/mnt/jenkins-workspace/workspace/operations-debs-vips-debian-glue/build-area/vips-tmp'
    gbp:info: Moving '/mnt/jenkins-workspace/workspace/operations-debs-vips-debian-glue/build-area/vips-tmp' to '/mnt/jenkins-workspace/workspace/operations-debs-vips-debian-glue/build-area/vips-7.32.3'
    gbp:debug: /bin/true ['-nc', '-S', '-us', '-uc'] []
    gbp:debug: rm ['-rf', '/mnt/jenkins-workspace/workspace/operations-debs-vips-debian-glue/build-area/vips-7.32.3'] []

That generates the orig tarball in /build-area/vips_7.32.3.orig.tar.gz

Then quilt cleanup is run and then:

    dpkg-buildpackage -uc -us -nc -d -S -i -I --source-option=--unapply-patches

That fails to find the original tarball which has been generated in /build-area

    + dpkg-buildpackage -uc -us -nc -d -S -i -I --source-option=--unapply-patches
    dpkg-buildpackage: source package vips
    dpkg-buildpackage: source version 7.32.3-1wmf3+0~20140213131304.3~1.gbpf0d6f3
    dpkg-buildpackage: source changed by jenkins-debian-glue Autobuilder <jenkins@integration-debian-builder.pmtpa.wmflabs>
     dpkg-source -i -I --unapply-patches --before-build source
    dpkg-buildpackage: warning: it is a bad idea to generate a source package without cleaning up first, it might contain undesired files.
     dpkg-source -i -I --unapply-patches -b source
    dpkg-source: error: can't build with source format '3.0 (quilt)': no upstream tarball found at ../vips_7.32.3.orig.tar.{bz2,gz,lzma,xz}
    dpkg-buildpackage: error: dpkg-source -i -I --unapply-patches -b source gave error exit status 255

I have:
* git-buildpackage 0.5.32 (from Ubuntu Precise)
* jenkins-debian-glue 0.8.0+0~20140204210212.11~1.gbpfb322f

**Comment by mika** [comment]
Nowadays we explicitly set `--git-export-dir=` by default, so this issue should no longer exist. Please reopen if you should notice any problems.
